### ISSUE TITLE
Fences are connecting to the post base

### ISSUE THREAD

**Issue by TheSnowyChickens** [TwistedGate/ImmersivePosts#1]
Hi,
this is only a slight "bug report", because it's only a visual thing. :=)

(I know, it is just a quality of life problem^^)

## What happend? *(Required)*
I placed *any* fence next to your post and they try to connect to the post. (that looks inappropriate)
(sadly the normal immersive posts has the same behaviour)

## Screenshot(s) *(Optional)*
![2019-04-22_01 24 36](https://user-images.githubusercontent.com/29357962/56476781-75c50500-649d-11e9-8a9e-1d16e7b8de7d.png)

![2019-04-22_01 29 06](https://user-images.githubusercontent.com/29357962/56476834-0bf92b00-649e-11e9-8196-ca128f1e1001.png)

![2019-04-22_01 34 51](https://user-images.githubusercontent.com/29357962/56476873-e91b4680-649e-11e9-80d6-cb8c7cc50819.png)

Can you change this behaviour ?

## Versions:
MC: 1.12.2
Forge: 2836
IE: 89
IP: 0.1.0

**Comment by TwistedGate** [comment]
Ah yes, forgot to do that. It's something that annoyed me with the original ones.
Thank you =)

**Comment by TheSnowyChickens** [comment]
Ty
