### ISSUE TITLE
SpongeForge 7.1.X messes with Immersive Post connected textures

### ISSUE THREAD

**Issue by Exymat** [TwistedGate/ImmersivePosts#10]
## What happend? *(Required)*
It was working for quite some time, and for an obscure reason, it is now no longer displaying fences connected textures vertically

## Screenshot(s) *(Optional)*
You have an image you'd like me to see? Throw it in!

![2020-02-27_02 44 59](https://user-images.githubusercontent.com/6762287/75404665-8343ea80-590b-11ea-8038-26de5f3e7341.png)

**Comment by TwistedGate** [comment]
Huh, that's an odd one.

Does it still happen after some time even when re-placing them or causing a block update next to one of the segments?

**Comment by TwistedGate** [comment]
Unable to reproduce, not sure what's going on there.

**Comment by Exymat** [comment]
Yep, still does. Even launching minecraft again, does not fix the issue. My friend, who uses the same modpack + configuration as me doesn't see it tho

**Comment by TwistedGate** [comment]
So 100% the exact same modpack configuration without any other mod additions on your side?

Also, can you give me the name of said pack, hoping i'd get it aswell to *maybe* see if can figure out what is going on exactly.

**Comment by Exymat** [comment]
100% the same. It a 'custom' modpack tho, but even then, nothing's explaining the issue

**Comment by TwistedGate** [comment]
Yeah im stumped aswell now.

**Comment by TwistedGate** [comment]
Imma just close this, if more people get it this will likely be re-opened.

**Comment by Exymat** [comment]
Yeah, fair enough. Got a little plot twist tho : doesn't happen in solo. I just don't know

**Comment by Exymat** [comment]
@TwistedGate Ok, I think I got it : my server is running with SpongeForge while my client doesn't have it, thus explaining why it was working perfectely fine in solo. I was able to reproduce the issue by installing the lastest version of SpongeForge on my client!

**Comment by TwistedGate** [comment]
Good to know.

**Comment by LiskoSlayer63** [comment]
I can confirm this, this exactly same issue happens to me when SpongeForge is installed on the server.

**Comment by KreativeKngYT** [comment]
Same, I have the same problem.
