### ISSUE TITLE
[1.14.4] Crash on startup

### ISSUE THREAD

**Issue by alexstratford** [TwistedGate/ImmersivePosts#13]
## What happend?
Mod crashes on startup, errors during "complete event phase"
Using version 1.14.4

Modlist:
Immersive Engineering 0.14-94
Pam's HC2 Trees
Pam's HC2 Crops
Pam's HC2 Food Core
Biomes O'Plenty
Clumps
Gates 1.5.0
HWYLA
Immersive Posts
ReAuth
RSGauges
Cooking For Blockheads
Engineer's Decor
AppleSkin
Create
JEI
Journeymap

## Crash Log
https://gist.github.com/alexstratford/5529e642f7de164e6ca15f1cd3a68376

## Screenshot(s)
![image](https://user-images.githubusercontent.com/58825136/78934418-cb296600-7aa2-11ea-96b9-a30fe595a6ba.png)

**Comment by TwistedGate** [comment]
It's seems like there's much more going on than just that, seeing how the log cries about missing models and so on.
i'll have to look into that.

**Comment by TwistedGate** [comment]
Fixed it crying about models and so on in 1.0.0-rev1.

*Aaanyway* Your problem is of the "Too low" IE Version kind.
1.0.0 and 1.0.0-rev1 have been compiled with IE-0.12-95

**Comment by TwistedGate** [comment]
Due to IE-0.12-95 not being officialy released as of this issue.

An [Alternate](https://www.curseforge.com/minecraft/mc-mods/immersiveposts/files/2927941) version has been uploaded to the mod page.

(For anyone else happening to see this issue)

**Comment by TheSnowyChickens** [comment]
Hello,

according to this issue, I found a weird condition in the 3.0.0 version for 1.16.4.

Sometimes it crash during boot and sometimes not, I don't know why, but I maybe think is could be the same issue.
-> 
[crash-2020-11-25_23.00.23-fml.txt](https://github.com/TwistedGate/ImmersivePosts/files/5599451/crash-2020-11-25_23.00.23-fml.txt)

MC: 1.16.4
Forge: 35.1.4
Immerisve Posts and Petroleum: 3.0.0
IE: 4.1.1

**Comment by TwistedGate** [comment]
@TheSnowyChickens Completely different type of issue, please create a seperate report.

Not to mention it's not even the same minecraft version
