### ISSUE TITLE
Pole Side addon (hammer interaction)

### ISSUE THREAD

**Issue by BeaterHouba** [TwistedGate/ImmersivePosts#14]
Greetings, I really like your mod it makes a lot easier to make long distance energy buses but i am missing 2 features:
1. Same as Immersive Engineering - When you put relay on bottom of pole side addon it will turn downwards
2. When you create pole side addon and put relay on top and bottom, it should make top and bottom pole side addon (i know this is not great description but I don't know how better to describe this)
I hope this screen makes my description more understandable :)
![2020-04-25_02 41 08](https://user-images.githubusercontent.com/63199402/80266995-252f4b80-869f-11ea-8139-73c79942ee87.png)

**Comment by TwistedGate** [comment]
> Same as Immersive Engineering - When you put relay on bottom of pole side addon it will turn downwards

They already do that, unless for some reason it aint working.
(In which case this would make this also a bug report)

> When you create pole side addon and put relay on top and bottom, it should make top and bottom pole side addon (i know this is not great description but I don't know how better to describe this)
I hope this screen makes my description more understandable :)

Yes i know ImmersiveIntergration had their arms do both up *and* down, but to be honest i was/am just too lazy to re-implement it.

**Comment by BeaterHouba** [comment]
Please don't be lazy :D Its awesome mod i like it but right now i am realy missing this feature because of high output of my Steam turbines and i dont want (can't) build 10 blocks high posts

**Comment by TwistedGate** [comment]
Alright. I'll see what i can do tomorrow :)

**Comment by TwistedGate** [comment]
86c05f0203fb1bb82d84f9734fd1f8a9ad974d1c

Thought i'd make it a 1.12.2 thing first cus why not. Felt like it.
1.14.4 will follow tomorrow.

**Comment by TwistedGate** [comment]
86c05f0203fb1bb82d84f9734fd1f8a9ad974d1c (1.12.2)
7fdfd10290473105e23d677417e9692a2a6a1ebe (1.14.4)
