### ISSUE TITLE
Extandable post missing texure

### ISSUE THREAD

**Issue by Pelemesh** [TwistedGate/ImmersivePosts#18]
## What happend? *(Required)*
Texture broke

## Crash Log  *(Required if available)*
```
nope
```

## Screenshot(s) *(Optional)*
https://gyazo.com/080b1daa477a198f7250d4838a316e27

## Additional context *(Optional)*
Missing part of the post texture if wire connector place on the bottom of double extended of that arm thingy.
Concrete slabs used as post
Optifine installed if thats relevant

**Comment by TwistedGate** [comment]
Ops...

**Comment by TwistedGate** [comment]
What MC version?

**Comment by Pelemesh** [comment]
1.12.2 sorry for late answer
Mod ver 0.2.1
Pack TFC reloaded

**Comment by TwistedGate** [comment]
Ah. Well i stopped support for 1.12.2 a while ago.

Just a guess, but if you have optifine installed that might screw with it. I remember it working fine with just IE and my addon.
