### ISSUE TITLE
Post arms are upside down after loading a saved game.

### ISSUE THREAD

**Issue by calloatti** [TwistedGate/ImmersivePosts#2]
## What happend? *(Required)*

Post arms are upside down after loading a saved game.

## Screenshot(s) *(Optional)*

![2019-04-26_15 38 36](https://user-images.githubusercontent.com/12817862/56829240-95f81980-6839-11e9-93ac-cd9069e32fd8.png)

Set up an example post:

![2019-04-26_15 49 54](https://user-images.githubusercontent.com/12817862/56829843-2d11a100-683b-11e9-868e-a921e9f78cfe.png)

Now exit the game and reload:

![2019-04-26_15 50 23](https://user-images.githubusercontent.com/12817862/56829848-313dbe80-683b-11e9-913e-f07e0df2b4ec.png)

## Additional context *(Optional)*

Forge Mod Loader version 14.23.5.2836 for Minecraft 1.12.2
ImmersiveEngineering-0.12-90-525
ImmersivePosts-0.1.1

**Comment by TwistedGate** [comment]
Yeah that was fixed in b385269a5779886c843298181fb0e82bf05b4ebd.
I noticed the bug while i was playing normaly myself the day after publishing the release. lol
