### ISSUE TITLE
[1.16.4] Random crash, which happens random

### ISSUE THREAD

**Issue by TheSnowyChickens** [TwistedGate/ImmersivePosts#20]
### Description of the issue
Hello,
sometimes Minecraft can boot normally, but sometimes not. (with your mod installed)
(example: modpack update -> first boot = crash, second boot = no crash, straight into the main menu)

### Versions and Modlist
MC: 1.16.4
Forge: 35.1.4
Immerisve Posts and Petroleum: 3.0.0
IE: 4.1.1
and some more mods in the log.

### Crash Log
https://pastebin.com/k2FZT0bk

### Screenshot(s)
*a normal "Forge has found an issue" screen*
(I was to slow to take a picture of it)

I am comming from the Issue 13 question. :)

**Comment by TwistedGate** [comment]
I've poked blu and malte about it and it's an multi-threading thing that has to be dealt with in IE rather than in my mod.

So they know about it and will trying fix it but there may still be a chance of it crashing then aswell.

I'll close this once they pushed the fix to their github.
