### ISSUE TITLE
Posts, when placed as fences, do not drop anything upon breaking them

### ISSUE THREAD

**Issue by MuteTiefling** [TwistedGate/ImmersivePosts#24]
### Description of the issue
Place down a post as if it were a fence, then break it with a pick axe. Nothing drops.
Place down an extendable post and insert posts items, then break it and you get everything back

### Versions and Modlist
immersiveposts-1.16.3-3.0.0
ImmersiveEngineering-1.16.5-4.2.1-131
forge: 36.0.7

Unrelated crash log for mod list: 
[crash-2021-02-04_12.17.56-client.txt](https://github.com/TwistedGate/ImmersivePosts/files/5935107/crash-2021-02-04_12.17.56-client.txt)

### Crash Log
No crash

### Screenshot(s)

https://streamable.com/1gu8qd

**Comment by MuteTiefling** [comment]
Oops, didn't look in PRs: https://github.com/TwistedGate/ImmersivePosts/pull/22

**Comment by TwistedGate** [comment]
Fixed for next (1.16.5) release

**Comment by MuteTiefling** [comment]
\o/ woo thanks!
