### ISSUE TITLE
"Tesselating block in world" when disguising the post base

### ISSUE THREAD

**Issue by robert-bowman** [TwistedGate/ImmersivePosts#27]
### Description of the issue
regardless of the block chosen to disguise the base (Solid, Opaque), the game immediately crashes and cannot be rejoined.  If the mod is removed and the game restarted, then all is well.  Everything else seems to work fine.

### Versions and Modlist (MOD Versions are listed in the crash log)
MC 1.16.5
Forge 36.0.43 
Immersive Engineering
Immersive Posts
JEI
JEI Integration

### Crash Log
Crash log is located at https://paste.ee/p/avmmb

Thank you for your attention.  :)

**Comment by TwistedGate** [comment]
This *should* be fixed by a9b92bad01c7b0c6e6d3e471014ab9bd80ba4a9b for next release (1.16.5)
