### ISSUE TITLE
[1.16.5] Crash- NoClassDefFoundError: blusunrize/immersiveengineering/client/utils/SinglePropertyModelData

### ISSUE THREAD

**Issue by ProsperCraft** [TwistedGate/ImmersivePosts#28]
### Description of the issue
I placed a "Extendable Post" from Immersive Posts, projected the multi-block "Diesel Generator" from Immersive Engineering on top of it. I then placed a 'pipe' from Immersive Engineering on top of the extendable post and immediately crashed. Now when I attempt to rejoin the world it happens again with the following error log - https://pastebin.com/pt7RcjRr
I am now stuck in a crash loop.

### Versions and Modlist
immersiveposts-1.16.3-3.0.0.jar

Modlist- https://www.curseforge.com/minecraft/modpacks/towncraft
TownCraft TWO for 1.16.5

### Crash Log
Frist crash on the server-
https://gist.github.com/ProsperCraft/f93a04732d8a2d26e9195399c26c5977
Replicated in single player-
https://pastebin.com/q2UVPTqN
https://pastebin.com/pt7RcjRr

### Screenshot(s)
Video-
https://cdn.discordapp.com/attachments/104694078595182592/818932039293206538/2021-03-09_11-41-28.mp4

**Comment by TwistedGate** [comment]
Try IE `1.16.5-4.2.2-132` and see if that get's rid of it. Which is the version Posts is compiled against

**Comment by ProsperCraft** [comment]
That isn't possible as that version does not load when silent gear is in the pack.  Forward compatibility is pretty important though no?

**Comment by TwistedGate** [comment]
I just now realized you're using `immersiveposts-1.16.3-3.0.0.jar` while `immersiveposts-1.16.5-4.0.0.jar` exists. Move to that please.
