### ISSUE TITLE
[1.16] Game crash on click with invalid block

### ISSUE THREAD

**Issue by Uebbels** [TwistedGate/ImmersivePosts#29]
I accidentally left clicked with a non supported block (PneumaticCraft Reinforced Brick Pillar) on the extendable post. I got an error message in chat, followed by a visible hitbox, but the "block" was completely invisible. The game then immediately crashed, and crashed on loading the world. I had to rollback to a backup in order to play the world.

Playing on the Direwolf20 Pack, version 1.65 -1.7.0
Crash Log: https://pastebin.com/sKXELkVw

**Comment by TwistedGate** [comment]
That crashlog is unrelated to what you describe, it's also a rather old version and was fixed in 4.0.0 of Immersive Posts
