### ISSUE TITLE
Breaking extendable posts converts fence into extendable base

### ISSUE THREAD

**Issue by gellis12** [TwistedGate/ImmersivePosts#3]
## What happened? *(Required)*
When breaking an extendable post base with one or more fences on it, the lowermost fence will be converted into an extendable post base.

## Additional context *(Optional)*
If you place an extendable post and attach N fences to it, the post will not drop N fences and 1 extendable post base when the base is mined, it'll drop N-1 fences and 2 extendable post bases instead.

**Comment by TwistedGate** [comment]
Ah yes, i fixed that one a while ago (58cb80091b236e9bc253528a82314a02115d1f4c)

Will be golden next release ;)

For the time being i recommend breaking the block above the base first befor breaking the base itself.
