### ISSUE TITLE
[1.16.5] Crash with Immersive Engineering v5.0.0

### ISSUE THREAD

**Issue by ghost** [TwistedGate/ImmersivePosts#30]
### Description of the issue
Minecraft fails to load when Immersive Posts is included in a pack with Immersive Engineering v5.0.0

### Versions and Modlist
Minecraft 1.16.5
Forge 36.1.24
ImmersiveEngineering-1.16.5-5.0.0-135
immersiveposts-1.16.5-4.0.0
jei-1.16.5-7.7.0.100

### Crash Log
https://pastebin.com/EmuscQAR

**Comment by TwistedGate** [comment]
Nobody ever reads the changelog it seems, but alright.. yeah i know

**Comment by ghost** [comment]
Sorry; I wasn't trying to seem impatient or demanding or anything like that. I understand and appreciate that you likely only work on these mods in your spare time and that you just hadn't had a chance to get to it yet. I just happened to have a crash log handy so thought I'd provide it in the event that it would be helpful in some way.

Thanks for all you do!
