### ISSUE TITLE
Crash after I placed a wrong block

### ISSUE THREAD

**Issue by emanuele246gi** [TwistedGate/ImmersivePosts#33]
### Description of the issue
I was building with a post next to me, then I misplaced a dirt block by clicking on the post like if I was trying to use dirt as a piece of the pole. After that it frozen my game and then it crashed, I try to rejoin the world but it keeps crashing

### Versions and Modlist
Immersive Engineering: 5.0.2-137
Immersive Posts: 4.1.0
Minecraft: 1.16.5
Forge: 36.1.33

The modlist is in the crash log

### Crash Log
https://pastebin.com/yedEe1Bw

**Comment by TwistedGate** [comment]
Darn it, i thought 5.0.2 IE was a pre-build

I fixed this already having found that myself 2 days ago (see 096136f571857f14b9056c3bc3e8ecefc7ffea40)

**Comment by TwistedGate** [comment]
Fixed in 4.1.1

**Comment by emanuele246gi** [comment]
Thank you so much!
