### ISSUE TITLE
[1.16.5] Unable to Open Engineer's Manual with Immersive Posts and Immersive Petroleum installed

### ISSUE THREAD

**Issue by Koku0** [TwistedGate/ImmersivePosts#34]
### Description of the issue
When IP or IPosts 4.2.0 are installed individually, the manual opens and all entries read fine. However, when both are installed, an error appears in the chatlog:
`1 entries failed to load! Please report this as an issue with your log file!`
The manual fails to open. This error does not occur with IPosts 4.1.1 installed.

**Expected Behaviour:**
Manual should open and display information normally.

### Versions and Modlist
Forge: 36.2.4
IE: 5.0.3-138
IP: 3.3.0-5
IPosts: 4.2.0

### Screenshot
![image](https://user-images.githubusercontent.com/47022005/131775555-a64d69ee-6652-42e6-b094-26576101db3b.png)

**Comment by TwistedGate** [comment]
i thought i fixed that crap.. *sigh*

**Comment by TwistedGate** [comment]
Anyone reading this.

Avoid updating for now...

**Comment by TwistedGate** [comment]
That was an accident..

Anyway, anyone reading this: Either don't update IPo or just dont use the Manual for now. Up to you.

**Comment by TwistedGate** [comment]
Should be fixed for both IP and IPo now.. go get the new releases

IP: `3.3.0-6`
IPo: `4.2.1`
