### ISSUE TITLE
Missing localization option for manual's index items.

### ISSUE THREAD

**Issue by Shellyoung** [TwistedGate/ImmersivePosts#4]
https://i.imgur.com/UE4iXAa.jpg
https://i.imgur.com/9520ZYq.png

**Comment by TwistedGate** [comment]
Ah yes, i'll work on getting that sorted out.

As of now (in 0.1.2) it's hardcoded for now, i completely forgot about localization at the time.

**Comment by TwistedGate** [comment]
Alright, everythings set. (Commit d5c34be3ed0c28face959230bbc31ad6280e76b5)

The en_us.lang changed a bit, because of it.

**Comment by Shellyoung** [comment]
I'll get it done in an hour or less.

**Comment by Shellyoung** [comment]
I'm a bit scared about the symbols "Â" here: <link;immersiveposts.posts;Â§oÂ§nhereÂ§r;0> Is it going to look well?

**Comment by TwistedGate** [comment]
Yeah, i just saw it and removed those in 5bb18c4d55d95d3eb2d8f3f8b4626fb5f9665056

Those were not supposed to be there :smiley:

**Comment by Shellyoung** [comment]
And the link leads to 0 page, is it ok? I'm asking because i didn't install the new version.

**Comment by TwistedGate** [comment]
It links to the `Accepted Blocks` entry. The thing you shown in your second screenshot.

**Comment by Shellyoung** [comment]
There must be also localization entry for the message: "Expected: Fence_name", or not? When you click extended post with inappropriate fence.

**Comment by TwistedGate** [comment]
Im not sure, because it's server sided. i'll look into it.

**Comment by Shellyoung** [comment]
Localization updated. I'll check it later if you will change something.

**Comment by TwistedGate** [comment]
Alright.

Sorry for being so chaotic lol

**Comment by Shellyoung** [comment]
It's fine :-)

**Comment by TwistedGate** [comment]
Done. 681c9832ecf30f8dfe51cac39daa8134191c7161

Only the very bottom of the language file changed this time. :D

**Comment by TwistedGate** [comment]
Alright, PR merged and i'll do the rest tomorrow. (releasing and stuff)

Thank you very much for your patience!
