### ISSUE TITLE
[Suggestion] Longer arms should also have up and down flipstates.

### ISSUE THREAD

**Issue by Ironnoob73** [TwistedGate/ImmersivePosts#42]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

![image](https://user-images.githubusercontent.com/67966070/204226545-ffa45c06-486f-477f-b2ec-8f2d6544d2bc.png)
![image](https://user-images.githubusercontent.com/67966070/204226746-22bda0fa-4ff9-4a98-bfd8-5788da364d86.png)
As shown in the figure above, although "arm_double" has a "down" state, the corresponding model is not displayed.

**Comment by TwistedGate** [comment]
If you had read the Manual, you'd know that the double arm _not_ flipping is intentional.

> As shown in the figure above, although "arm_double" has a "down" state, the corresponding model is not displayed.

And that right there, is a bug..
