### ISSUE TITLE
[BUG] Missing recipes for IPo-Fences

### ISSUE THREAD

**Issue by rrrr4201** [TwistedGate/ImmersivePosts#46]
### Does this suggestion already exist?

- [X] Yes, i have searched for already existing suggestions and found none.

### Feature Explanation

![2023-06-04_15 21 15](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/1acc9d81-bb7e-4c54-bdd7-9ee8cbf6db1b)
![2023-06-04_15 21 16](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/74456a27-a416-4856-91aa-d528c742b9a4)
![2023-06-04_15 21 20](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/47493e15-a8b3-4eea-8430-4c82e11fe8f4)
Clicking Iron Fence does not show the recipe for the Iron Fence
![2023-06-04_15 21 21](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/649ae8f7-4aa8-4ac3-838c-ad445e9bb85d)
Clicking Uranium Fence does not show the recipe for the Uranium Fence (same from Iron to Uranium fences)
![2023-06-04_15 20 00](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/25c356f5-d2a8-40e0-9620-233b3aa07176)
![2023-06-04_15 20 02](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/e1d86db9-f842-4da9-90b3-bce7c04c05f0)
![2023-06-04_15 20 03](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/7b9a2b4f-52db-46ff-8d4b-acf10e11c706)
![2023-06-04_15 20 05](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/34fceda9-1970-48c7-8ae8-53656f81c873)
![2023-06-04_15 20 07](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/e9297aec-6319-4627-bafe-94f13f413d5d)
Engineer's Manual shows a weird recipe for the Iron Fence, is this a bug/mistake?
![2023-06-04_15 20 08](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/f1ea9f0b-6927-4aec-8f3f-ef41c141f4e2)
![2023-06-04_15 20 08_2](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/cda5af08-2e79-4ace-8b17-f490386adf84)
![2023-06-04_15 20 09](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/eed46bec-42f3-4c99-9ed7-25c6861a8dbd)
![2023-06-04_15 21 13](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/3b559f30-a55e-48ad-ad46-2750d9f51b81)

As shown in the screenshots posted above, there are NO RECIPES available for immersive fences except treated wood, steel, aluminum, and nether brick (vanilla) fences.

I am not sure if this is a bug caused by other mods, so I have attached possible conflicting mods and the entire list of mods that I am using. If this is a bug, please fix it so that I can use these fences in the survival game mode.

If it is a 'feature' that these fences are 'uncraftable' please make crafting recipes ASAP, as I don't see the point of adding blocks if they are not craftable.

Thanks!

_Edit: there are no recipes for the sticks used for the fences as well. The fences themselves have no recipes too.
For the extendable posts, pressing **shift** while hovering a cursor on them DOES NOT display any descriptions._

**Forge Version:** 1.19.2-forge-43.2.11
**Immersive Engineering:** ImmersiveEngineering-1.19.2-9.2.2-165
**Immersive Posts:** ImmersivePosts-1.19.2-4.3.0-6
**Create:** create-1.19.2-0.5.0.i
**Create Crafts & Additions:** createaddition-1.19.2-20230507a

![image](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/74d892fc-7488-46fd-8bfa-750a0aab81eb)

**Comment by TwistedGate** [comment]
What does the world config (`immersiveposts-server.toml`) look like?

**Comment by rrrr4201** [comment]
> What does the world config (`immersiveposts-server.toml`) look like?

![image](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/3b7fb7af-bb95-4c03-b9b6-fd5f21f1f894)
![image](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/e6797149-3d1e-4213-8dd1-2f1260d45964)
Here is the immersiveposts-server.toml file's location

![image](https://github.com/TwistedGate/ImmersivePosts/assets/129680167/f5146461-4043-4a65-b7d9-c3da010cceb0)
The world config file opened with Notepad.

Thank you for your support, dear developer TwistedGate!

**Comment by TwistedGate** [comment]
What in the world lol

Same thing in a fresh instance with *just* Immersive Engineering and Immersive Posts?

**Comment by rrrr4201** [comment]
> What in the world lol
> 
> Same thing in a fresh instance with _just_ Immersive Engineering and Immersive Posts?

I just tested with JUST Immersive Engineering and Immersive Posts. I still can't find recipes for them.
Btw, I am not particularly sure what you mean by "fresh instance."
I have removed all the other mods from the mods file except Immersive Engineering and Immersive Posts and ran the game.
If there is a particular way to initiate the "fresh instance," please let me know.

**Comment by TwistedGate** [comment]
Forgot to tell, but i did some testing localy aswell and sure enough for some reason the recipes are completely missing.
i'll trying figure this out as soon as i can.

In the meantime you could make a datapack if you **realy** want them.

And sorry, i don't know how this has gone unnoticed for *so long*.

PS: Next time please make sure you actualy use the right template. If it feels like a bug/glitch it likely is, and there is a template for those specificaly.

**Comment by TwistedGate** [comment]
Fixed now by just dumping the config options to disable them. (Just datapack the fence recipes away if needed and thats it)
